name: weatherapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.9 <4.0.0"

dependencies:
  async: ^2.10.0
  bloc_test: ^9.1.1
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  envied: ^0.3.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_comms: ^0.0.6+2
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.2
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.8.0
  leancode_hooks: ^0.0.3+1
  logging: ^1.1.1
  meta: ^1.8.0
  oktoast: ^3.3.1
  path_provider: ^2.0.14
  provider: ^6.0.5
  rxdart: ^0.27.7
  shimmer_animation: ^2.1.0+1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  leancode_lint: ^2.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/resources
