name: flutter prepare

on:
  pull_request:
    branches: [master]
    paths:
      - "mobile/**"

jobs:
  main:
    name: Flutter ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.7.9

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.6.2
        with:
          flutter-version: ${{ matrix.version }}

      - name: flutter pub get
        run: flutter pub get
        
      - name: build_runner
        env: 
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test

      - name: flutter format
        run: dart format --set-exit-if-changed .